title: HydroQuantum
tagline: Quantum Computing for Hydrology and Water Resources
description: >-
 HydroQuantum is a platform advancing the application of quantum computing in hydrology and water resources. 
 It develops and integrates quantum algorithms and quantum-enhanced machine learning to improve modeling, prediction, 
 optimization, and uncertainty quantification in complex water systems. All codes, publications, and training materials 
 are freely available. We welcome collaboration and discussion on quantum-related modeling and simulations in hydrology 
 and water resources.
  
email: samadi@clemson.edu
url: "https://HydroQuantum.github.io"
baseurl: ""
lang: en
markdown: kramdown
permalink: pretty
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

collections:
  publications:
    output: true
    permalink: /publications/:name/
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: publications
    values:
      layout: publication
  - scope:
      path: ""
      type: projects
    values:
      layout: project

