title: HydroQuantum
tagline: Quantum Computing for Hydrology and Water Resources
description: >-
 HydroQuantum is a research initiative within Clemson University’s HHR Lab focused on quantum computing and quantum machine learning applications in hydrology and water resources.
  
email: samadi@clemson.edu
url: "" # before deploying use url: "https://clemson-hydroinformatics-lab.github.io"
baseurl: "" # before deploying use baseurl: "/HydroQuantum.github.io", or empty if hosted at the root of a domain
lang: en
markdown: kramdown
permalink: pretty
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

collections:
  publications:
    output: true
    permalink: /publications/:name/
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: publications
    values:
      layout: publication
  - scope:
      path: ""
      type: projects
    values:
      layout: project

